//! Mutated Arithmetic Handlers
//!
//! This file is conditionally compiled based on build-time mutation selection.
//! Each build generates different handler implementations.
//!
//! Generated by build.rs - DO NOT EDIT MANUALLY

// Allow intentional identity operations (like JUNK[0] ^ JUNK[0] = 0) for obfuscation
#![allow(clippy::eq_op)]

// Include the build-time generated mutations
include!(concat!(env!("OUT_DIR"), "/mutated_handlers.rs"));
